name: provisioner01
services:

    master_ct:
        container_name: master_ct
        build: ./master_ct/
        environment:
            - TZ=Europe/Madrid
        command: ansible --version